AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Drop-the-ropes serverless API


Globals:
  Function:
    Timeout: 3

Resources:
  DropTheRopesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: drop_the_ropes/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DropTheRopes:
          Type: Api
          Properties:
            Path: /dtr
            Method: get

Outputs:
  DropTheRopesApi:
    Description: "API Gateway endpoint URL for Prod stage for Drop The Ropes function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dtr/"
  DropTheRopesFunction:
    Description: "Drop The Ropes Lambda Function ARN"
    Value: !GetAtt DropTheRopesFunction.Arn
  DropTheRopesFunctionIamRole:
    Description: "Implicit IAM Role created for Drop The Ropes function"
    Value: !GetAtt DropTheRopesFunctionRole.Arn
